### ISSUE TITLE
RoMe got aborted by the system when evalauting some specific texts

### ISSUE THREAD

**Issue by cyr19** [rashad101/RoMe#1]
Hello,

thank you very much for releasing the code for this work!

using the default setting of RoMe, the program got aborted due to some memory allocation issues like “*** Error in `python': corrupted size vs. prev_size: 0x000055ee10091dd0 ***” or “python *** Error in `python': free(): invalid next size (fast)”.

I noticed that it occurs only when evaluating some specific texts, for example:

hyp = "Cheb's neighbors from the German side of the border gave performances including some with reconstructed Jak 18T aircraft and three-member formations using Bücker Jungmann biplanes"
ref = "Germany's neighbors in Chisinau demonstrated with reconstructed aircraft How 18t or three formations dvouplošníků Bücker Jungmann." (for this one, when removing the word "dvouplošníků", RoMe could work.)

hyp = "Since then, the physicists have referred to the possibility of additional small spatial dimensions as the Kaluza-Klein Theory."
ref = "Since then physicists call the possibility of additional small spatial dimensions Kaluzovou-Kleinovou theories."

I recreated exactly the same environment as required, but it still doesn't work.

Could you please help me out? Thanks a lot!

Kind regards,

**Comment by rashad101** [comment]
Hi cry19,

The issues is fixed now. Please pull the latest version of the code and run again. Let me know if the issue still persists on your side.

Best regards,
Rashad

**Comment by rashad101** [comment]
Hi cry19,

The issues is fixed now. Please pull the latest version of the code and run again. Let me know if the issue still persists on your side.

Best regards,
Rashad
