### ISSUE TITLE
Readme missing some installation steps

### ISSUE THREAD

**Issue by vasanthsarathy** [rashad101/RoMe#2]
While trying to install RoMe, I came across a few more things I needed to do to get it to work on my machine:

1. Download stanza model, by opening up a python interpreter, and: 

```
import stanza
stanza.download('en')
stanza_nlp = stanza.Pipeline('en')
```

2. Download pretrained fasttext bin and vec  files

- download it from https://dl.fbaipublicfiles.com/fasttext/vectors-wiki/wiki.simple.zip
- extract contents into `data/`

Maybe worthwhile putting this into the README file. :)

**Comment by rashad101** [comment]
Hi Vasanthsarathy,

I just fixed the issue. Thanks for suggestion.

Best regards,
Rashad
